### ISSUE TITLE
Authentication times out when switch hostname is different than ansible inventory hostname

### ISSUE THREAD

**Issue by rogerfachini** [stackhpc/ansible-role-dell-powerconnect-switch#4]
Hello, and thanks for making such an awesome role! I've been using this to set up a PowerConnect 5524 switch in my homelab, and I ran into a small issue. The role would hang at the login prompt, and never actually attempt to log into the switch, or apply configuration. 

On further investigation I found out that the problem was being caused by the four `prompt` regexps in the `vars/main.yml` file. By default the prompt regexps assume the switch is already configured with a hostname that matches ansible's `inventory_hostname`, but this is not true on an unconfigured switch. In my case, the PowerConnect 5524 defaults to a hostname of `console` when one is not configured, so I was able to tweak the regexps as follows:
```
dell_powerconnect_main_prompt: "({{ inventory_hostname }}|console)#[\\s]?"
dell_powerconnect_config_prompt: "({{ inventory_hostname }}|console)\\(config(-vlan)?\\)#[\\s]?"
dell_powerconnect_interface_prompt: "({{ inventory_hostname }}|console)\\(config-if.*\\)#[\\s]?"
dell_powerconnect_enable_prompt: "({{ inventory_hostname }}|console)>[\\s]?"
```
This fix worked for me, however it may not be a general enough solution, since other models of switch may default to a hostname other than `console`. I'll do some more experimentation, and submit a PR when I find a better solution.

**Comment by markgoddard** [comment]
Thanks for raising this Roger, look forward to your PR.
